services:
  - type: web
    name: vertx-app
    runtime: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: DB_HOST
        value: localhost
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: Abhinav@91
      - key: DB_NAME
        value: mikomini_app_db
